services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kubsu
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
    ports:
      - "5432:5432"
    restart: unless-stopped
    
